"""Markdown reporter for scan results."""

from datetime import UTC, datetime
from pathlib import Path

from scanner.core.scanner import ScanResult, ScanSummary
from scanner.scoring.calculator import get_risk_emoji


def generate_markdown_report(
    summary: ScanSummary,
    output_path: str | Path | None = None,
) -> str:
    """Generate Markdown report from scan summary.

    Args:
        summary: Scan summary with all results
        output_path: Optional path to write Markdown file

    Returns:
        Markdown string of the report
    """
    timestamp = datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%S UTC")
    risk_emoji = get_risk_emoji(summary.risk_level)

    lines = [
        "# LLM Red Teaming Report",
        "",
        f"**Target Model:** {summary.model}",
        f"**Scan Date:** {timestamp}",
        f"**Patterns Tested:** {summary.scanned}",
        f"**Duration:** {summary.duration_seconds:.1f} seconds",
        "",
        "---",
        "",
        "## Executive Summary",
        "",
        f"**Overall Risk Level:** {risk_emoji} **{summary.risk_level}**",
        "",
        f"- 🔴 Critical: {_count_risk(summary.results, 9.0, 10.0)} vulnerabilities",
        f"- 🟠 High: {_count_risk(summary.results, 7.0, 8.9)} vulnerabilities",
        f"- 🟡 Medium: {_count_risk(summary.results, 4.0, 6.9)} vulnerabilities",
        f"- 🟢 Low: {_count_risk(summary.results, 0.0, 3.9)} vulnerabilities",
        "",
        "---",
        "",
        "## Statistics",
        "",
        "| Classification | Count | Percentage |",
        "|---------------|-------|------------|",
        f"| COMPROMISED | {summary.vulnerable} | "
        f"{_pct(summary.vulnerable, summary.scanned)} |",
        f"| REFUSED | {summary.refused} | "
        f"{_pct(summary.refused, summary.scanned)} |",
        f"| PARTIAL | {summary.partial} | "
        f"{_pct(summary.partial, summary.scanned)} |",
        f"| ERROR | {summary.errors} | "
        f"{_pct(summary.errors, summary.scanned)} |",
        "",
        "---",
        "",
        "## Detailed Findings",
        "",
    ]

    # Sort by risk score descending
    sorted_results = sorted(
        summary.results, key=lambda x: x.risk_score, reverse=True
    )

    for i, result in enumerate(sorted_results, 1):
        risk_emoji = get_risk_emoji(
            "CRITICAL" if result.risk_score >= 9.0
            else "HIGH" if result.risk_score >= 7.0
            else "MEDIUM" if result.risk_score >= 4.0
            else "LOW"
        )
        status_emoji = {
            "COMPROMISED": "🔴",
            "REFUSED": "🟢",
            "PARTIAL": "🟡",
            "ERROR": "⚪",
        }.get(result.classification, "⚪")

        lines.extend([
            f"### {i}. {result.pattern_name} ({result.classification})",
            "",
            f"- **Pattern ID:** `{result.pattern_id}`",
            f"- **Category:** {result.category}",
            f"- **Severity:** {result.severity}/10",
            f"- **Risk Score:** {result.risk_score:.1f}/10 {risk_emoji}",
            f"- **Classification:** {status_emoji} {result.classification}",
            f"- **Confidence:** {result.confidence:.1%}",
            "",
            "**Payload:**",
            "```",
            result.payload[:500],
            "```",
            "",
        ])

        if result.response:
            lines.extend([
                "**Model Response:**",
                "```",
                result.response[:500],
                "```",
                "",
            ])

        if result.error:
            lines.extend([
                "**Error:**",
                "```",
                result.error,
                "```",
                "",
            ])

        lines.append("---")
        lines.append("")

    # Footer
    lines.extend([
        "## Methodology",
        "",
        "This report was generated by LLM Red Team Scanner v0.1.0.",
        "Testing follows OWASP Top 10 for LLM Applications guidelines.",
        "",
        "### References",
        "",
        "- [OWASP Top 10 for LLM Applications](https://owasp.org/www-project-top-10-for-large-language-model-applications/)",
        "- [NVIDIA Garak](https://github.com/NVIDIA/garak)",
        "",
    ])

    content = "\n".join(lines)

    if output_path:
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

    return content


def _count_risk(
    results: list[ScanResult], low: float, high: float
) -> int:
    """Count results in risk score range."""
    return sum(1 for r in results if low <= r.risk_score <= high)


def _pct(count: int, total: int) -> str:
    """Calculate percentage string."""
    if total == 0:
        return "0.0%"
    return f"{count/total*100:.1f}%"
